name: Auto-merge dev into main

on:
  workflow_run:
    workflows: ["CI on dev"]
    types:
      - completed
    branches:
      - dev

jobs:
  merge:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (main)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch dev branch
        run: git fetch origin dev:dev

      - name: Merge dev into main
        run: |
          git merge --no-ff dev -m "Automated merge of dev into main [skip ci]"

      - name: Push changes to main
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
